 var json={
 	"list":[
 		{
 			"id":"0",
 			"mz":"王宏",
 			"pic":[
 				'../img/pic/1.jpg',
 				'../img/pic/4.jpg',
 				'../img/pic/3.jpg',
 				'../img/pic/2.jpg'
 			],
 			"xm":"有理想的前段设计师",
 			"tx":"../img/pic/1_1.jpg"
 		},
 		{
 			"id":"1",
 			"mz":"张三",
 			"pic":[
 				'../img/pic/5.jpg',
 				'../img/pic/6.jpg'
 			],
 			"xm":"我排行老三",
 			"tx":"../img/pic/1_2.jpg"
 			
 		},
 		{
 			"id":"2",
 			"mz":"老王",
 			"pic":[
 				'../img/pic/7.jpg',
 				'../img/pic/8.jpg',
 				'../img/pic/9.jpg',
 				'../img/pic/10.jpg',
 				'../img/pic/11.jpg'
 			],
 			"xm":"有理的隔壁老王",
 			"tx":"../img/pic/1_3.jpg"
 		},
 		{
 			"id":"3",
 			"mz":"李四",
 			"pic":[
 				'../img/pic/12.jpg',
 				'../img/pic/13.jpg',
 				'../img/pic/14.jpg'
 			],
 			"xm":"我排行老师",
 			"tx":"../img/pic/1_4.jpg"
 		}
 		
 	]
 }
